config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env["devise.mapping"] = Devise.mappings[scope]
      true
    end
    constraints(constraint) do
      yield
    end
  end


  root :to => 'users#top'
  get 'users/about'
  get "users/hide" => "users#hide", as: 'users_hide'
  patch "users/withdrawal" => "users#withdrawal", as: 'users_withdrawal'
  get "search" => "search#search"

  resources :users, only: [:show,:index,:edit,:update] do
    get 'relationships/index'
    get 'relationships/following/:user_id' => 'users#following'
    get 'relationships/follower/:user_id' => 'users#follower'
  end
  resources :relationships, only: [:create,:destroy]
  resources :messages, only: [:create,:destroy]
  resources :rooms, only: [:create, :show, :index]

  mount ActionCable.server => '/cable'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image, destroy: false
  include JpPrefecture
  jp_prefecture :area
  # has_one_attached :image#ファイルアップロード用?

  enum status: { 楽しく遊びたい!: 0, 実力を試してみたい!: 1, 演奏会ができるレベルまでやりたい!: 2, 本気で頑張りたい!: 3 }

  has_many :user_instruments
  has_many :instruments, through: :user_instruments
  has_many :user_genres
  has_many :genres, through: :user_genres
  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries

# 能動的関係=フォローしている人の情報
  has_many :relationships, foreign_key: 'following_id', dependent: :destroy # フォローしてる人取得？
  has_many :followings, through: :relationships, source: :follower # sourceはモデルから　# 自分がフォローしている人
# 受動的関係＝フォロワー、フォローしてくる人の情報
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # フォロワー取得
  has_many :followers, through: :reverse_of_relationships, source: :following # 自分をフォローしている人

# throughオプションによりrelationships経由でfollowings・followersにアクセスできるようになる＝relationshipは中間テーブルであるという意味付け
# = 架空のモデルを介して、対象のモデルと多対多の関連付け => これにより情報抽出可能
# sourceオプション = has_many :through関連付けの関連付け元（従属するモデル※今回はモデルではないもの〔follow〕も含む）名を指定する
# foreign_keyオプション = 関連付けるモデルを指す外部キー(FK)のカラム名を設定する。このオプションを使用しなければ、「belongs_toの引数_id」が指定される
# = follower_idを入り口としてねっていう意味。sourceは出口。
# following_id = 人、follower_id = アンカー　人とアンカーは紐で繋がってる（relationshipテーブル）


#フォローする
  def follow(other_user)#other_userには、例えばfollowing = current_user.follow(user)の()内が自動で代入される
    unless self == other_user
      self.relationships.find_or_create_by(follower_id: other_user.id)
    end
  end

#フォローを外す
  def unfollow(other_user)
    relationship = self.relationships.find_by(follower_id: other_user.id)
    relationship.destroy if relationship #existなら
  end

#フォローしてるか確認する(してればtrueを返す)
  def following?(other_user)
    self.followings.include?(other_user)
  end


  validates :name, presence: true, uniqueness: true
  before_save { self.email = email.downcase }
  validates :email, presence: true, uniqueness: true
  validates :experience, numericality: { only_integer: true }, allow_blank: true
  validates :history, length: {maximum: 100}
  validates :introduction, length: {maximum: 200}

  def remember_me
    true
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :ensure_correct_user, only: [:edit, :update, :hide, :withdrawal]

	def top
		@instruments = Instrument.all
		@genres = Genre.all
	end

	def about
	end

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	    @currentUserEntry = Entry.where(user_id: current_user.id)
	    @userEntry=Entry.where(user_id: @user.id)
	    unless @user.id == current_user.id
	      @currentUserEntry.each do |cu|
	        @userEntry.each do |u|
	          if cu.room_id == u.room_id then
	            @isRoom = true
	            @roomId = cu.room_id
	          end
	        end
	      end

	      unless @isRoom
	        @room = Room.new
	        @entry = Entry.new
	      end
	    end
	end

	def edit
	end

	def update
		if @user.update(user_params)
	      redirect_to user_path(@user), notice: "You have updated user successfully."
	    else
	      render "edit"
	    end
	end

	def hide
	end

	def withdrawal
        @user.update(is_deleted: true)
        reset_session
        redirect_to root_path
	end


	private

    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :image, :area, :experience, :stance, :history, :introduction, :is_deleted)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
about,,

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th>follows</th>
					<th>followers</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td><%= user.relationships.count %></td>
					<td><%= user.reverse_of_relationships.count %></td>
					<td><% unless current_user == user %>
						<% if current_user.following?(user) %>
						    <%= form_for(current_user.relationships.find_by(follower_id: user.id), html: { method: :delete }) do |f| %>
						      <%= hidden_field_tag :follower_id, user.id %>
						      <%= f.submit 'Unfollow', class: 'btn btn-danger' %>
						    <% end %>
						<% else %>
						    <%= form_for(current_user.relationships.build) do |f| %>
						      <%= hidden_field_tag :follower_id, user.id %>
						      <%= f.submit 'Follow', class: 'btn btn-primary' %>
						    <% end %>
						<% end %>
						<% end %></td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/users/show.html.erb
<h3>ユーザー詳細</h3>
<h2><%= @user.name %></h2>

<div class="row">
  <% if current_user == @user %>
    <%= link_to '', edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
  <% end %>
</div>

<% unless @user.id == current_user.id %>
  <% if @isRoom == true %>
    <%= link_to "チャット", room_path(@roomId) %>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める" %>
    <% end %>
  <% end %>
<% end %>

app/views/users/top.html.erb
<div class='home-main'>
  <div class='home-wrapper'>
    <div class='home-header'>
      <div class='home-header-content'>
		<div class='top-message-box'><h1> 「音アワセ」しよう！ </h1></div>
        <div class='search-form'>
          <div class='form-explanation'><h2> キーワードから探す</h2></div>
	      <span class='search-box'>
	      	<%= form_tag(search_path, :method => 'get') do %>
              <%= text_field_tag 'search[content]' %>
              <%= select_tag 'search[method]', options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
              <%= submit_tag 'Search' %>
            <% end %>
            <!-- <p>詳細検索</p> -->
            <!-- <p>= search_form_for(@q, url: search_path) do |f|
              = f.text_field :instrument_name_cont, placeholder: 'エリア[例：下北沢]', autocomplete: :off, class: 'search-box__content left-content', id: 'instrument-search-field'
              = f.text_field :name_or_outline_or_instruments_name_or_genres_name_cont, placeholder: 'キーワード[例：yohji yamamoto]', autocomplete: :off, class: 'search-box__content center-content', id: 'keyword-field'
              = select_tag :rate_range, options_from_collection_for_select(RateRange.all, :id, :name), { prompt: "評価", class: 'search-box__content right-content', id: 'rate-field'}
              = f.submit '検 索', class: 'search-box__submit', id: 'search-submit-btn'</p> -->
	      </span>
          <div id='search-result'>
            <div class='candidate-list'></div>
          </div>
		</div>
	  </div>
    </div>
    <div class="top-wrapper">
      <div class='top-main'>
		<div class='search-instrument'>
		  <h2 class='search-instrument__title'><span>　楽器から探す </span></h2>
		  <div class='search-instrument__area'>
<!-- 		    <ul class='top-instruments'>
			  <%# @top_instruments.each do |top_instrument| %>
			    <li class='top-instrument'>
			      <%#= link_to(search_path(@q, 'q[instruments_name_eq]': top_instrument.name), class: 'top-instrument-link') do %>
			        <%#= image_tag asset_path(top_instrument.image), class: 'top-instrument__img' %>
			      <%# end %>
			    </li>
			  <%# end %>
			</ul> -->


			<%= form_tag(search_path, :method => 'get') do %>
              <% @instruments.each do |instrument| %>
			    <li class='all-instrument'>
			      <%= link_to(search_path, class: 'instrument-link') do %>
			        <span><%= instrument.name %></span>
			      <% end %>
			    </li>
			  <% end %>
              
            <% end %>
         

			</div>
		</div>
		<div class='search-genre'>
<!-- 		    <p>%h2.search-genre__title
		      %span ジャンルから探す
		    .search-genre__area
		      %ul.top-genres
		        - @top_genres.each do |top_genre|
		          %li.top-genre
		            = link_to(shops_search_path(@q, 'q[genres_name_eq]': top_genre.name), class: 'top-genre-link') do
		              = image_tag asset_path(top_genre.image), class: 'top-genre__img'
		              .top-genre__name
		                %span= top_genre.name
		              .top-genre__store-count
		                %span= "#{top_genre.shops.count}件"
		      %ul.genre-list.clearfix
		        - @genres.each do |genre|
		          %li.all-genre
		            = link_to(shops_search_path(@q, 'q[genres_name_eq]': genre.name), class: 'genre-link') do
		              %span= genre.name</p> -->
		</div>
		<div class='search-area'>
<!-- 		  <p>%h2.search-area__title
		      %span 地域から探す
		    .search-area__area
		      .selected-area
		        .selected-area__name
		          %span 東京
		        .selected-area__store-count
		          %span= "#{@shops.count}件"
		      %ul.top-areas
		        - @top_areas.each do |top_area|
		          %li.top-area
		            = link_to(shops_search_path(@q, 'q[area_name_cont]': top_area.name), class: 'top-area-link') do
		              .top-area-box
		                %span.top-area-name= top_area.name
		                %span.top-area-shop-count= "#{top_area.shops.count}件"
		      %ul.area-list.clearfix
		        - @areas.each do |area|
		          %li.all-area
		            = link_to(shops_search_path(@q, 'q[area_name_cont]': area.name), class: 'area-link') do
		              %span= area.name</p> -->
		</div>
	  </div>
    </div>
  </div>
</div>