config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env["devise.mapping"] = Devise.mappings[scope]
      true
    end
    constraints(constraint) do
      yield
    end
  end


  root :to => 'users#top'
  get 'users/about'
  get "users/hide" => "users#hide", as: 'users_hide'
  patch "users/withdrawal" => "users#withdrawal", as: 'users_withdrawal'
  get "search" => "search#search"

  resources :users, only: [:show,:index,:edit,:update] do
    get 'relationships/index'
    get 'relationships/following/:user_id' => 'users#following'
    get 'relationships/follower/:user_id' => 'users#follower'
  end
  resources :relationships, only: [:create,:destroy]
  resources :messages, only: [:create,:destroy]
  resources :rooms, only: [:create, :show, :index]

  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/genre.rb
class Genre < ApplicationRecord

  belongs_to :user, optional: true
  has_many :user

  attachment :image, destroy: false

end

app/models/instrument.rb
class Instrument < ApplicationRecord

  belongs_to :user, optional: true#外部キーがnilでも保存可
  has_many :user

  attachment :image, destroy: false

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: {maximum: 200}

  after_create_commit { MessageBroadcastJob.perform_later self }

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :following, class_name: 'User', foreign_key: :following_id
  belongs_to :follower, class_name: 'User', foreign_key: :follower_id

  validates :following_id, presence: true
  validates :follower_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages
  has_many :entries
  has_many :users, through: :entries

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image, destroy: false
  include JpPrefecture
  jp_prefecture :area
  # has_one_attached :image#ファイルアップロード用?

  enum status: { 楽しく遊びたい!: 0, 実力を試してみたい!: 1, 演奏会ができるレベルまでやりたい!: 2, 本気で頑張りたい!: 3 }

  has_many :user_instruments
  has_many :instruments, through: :user_instruments
  has_many :user_genres
  has_many :genres, through: :user_genres
  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries

# 能動的関係=フォローしている人の情報
  has_many :relationships, foreign_key: 'following_id', dependent: :destroy # フォローしてる人取得？
  has_many :followings, through: :relationships, source: :follower # sourceはモデルから　# 自分がフォローしている人
# 受動的関係＝フォロワー、フォローしてくる人の情報
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # フォロワー取得
  has_many :followers, through: :reverse_of_relationships, source: :following # 自分をフォローしている人

# throughオプションによりrelationships経由でfollowings・followersにアクセスできるようになる＝relationshipは中間テーブルであるという意味付け
# = 架空のモデルを介して、対象のモデルと多対多の関連付け => これにより情報抽出可能
# sourceオプション = has_many :through関連付けの関連付け元（従属するモデル※今回はモデルではないもの〔follow〕も含む）名を指定する
# foreign_keyオプション = 関連付けるモデルを指す外部キー(FK)のカラム名を設定する。このオプションを使用しなければ、「belongs_toの引数_id」が指定される
# = follower_idを入り口としてねっていう意味。sourceは出口。
# following_id = 人、follower_id = アンカー　人とアンカーは紐で繋がってる（relationshipテーブル）


#フォローする
  def follow(other_user)#other_userには、例えばfollowing = current_user.follow(user)の()内が自動で代入される
    unless self == other_user
      self.relationships.find_or_create_by(follower_id: other_user.id)
    end
  end

#フォローを外す
  def unfollow(other_user)
    relationship = self.relationships.find_by(follower_id: other_user.id)
    relationship.destroy if relationship #existなら
  end

#フォローしてるか確認する(してればtrueを返す)
  def following?(other_user)
    self.followings.include?(other_user)
  end


  validates :name, presence: true, uniqueness: true
  before_save { self.email = email.downcase }
  validates :email, presence: true, uniqueness: true
  validates :experience, numericality: { only_integer: true }, allow_blank: true
  validates :history, length: {maximum: 100}
  validates :introduction, length: {maximum: 200}

  def remember_me
    true
  end

end

app/models/user_genre.rb
class UserGenre < ApplicationRecord

  belongs_to :user
  belongs_to :genre

end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord

  belongs_to :user
  belongs_to :instrument

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

before_action :authenticate_user!

  def create
  end

  def destroy
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

before_action :authenticate_user!

  def index
  end

  def create
  	@room = Room.create(:name => "")
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)#自分の分
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))#相手の分
    redirect_to room_path(@room.id)
  end

  def show
  	@room = Room.find(params[:id])
    #present?の戻り値は真偽値。よって、trueの場合、
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @content = params["search"]["content"]
    @method = params["search"]["method"]
    @records = search_for(@content, @method)
  end

  private

  def search_for(content, method)
	if method == 'perfect'
	  User.where(name: content)
	elsif method == 'forward'
	  User.where('name LIKE ?', content+'%')
	elsif method == 'backward'
	  User.where('name LIKE ?', '%'+content)
	else
	  User.where('name LIKE ?', '%'+content+'%')
	end
  end

end

# .or(User.where(Instrument.find(content).user_id: content))

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :ensure_correct_user, only: [:edit, :update, :hide, :withdrawal]

	def top
		@instruments = Instrument.all
		@genres = Genre.all
	end

	def about
	end

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	    @currentUserEntry = Entry.where(user_id: current_user.id)
	    @userEntry=Entry.where(user_id: @user.id)
	    unless @user.id == current_user.id
	      @currentUserEntry.each do |cu|
	        @userEntry.each do |u|
	          if cu.room_id == u.room_id then
	            @isRoom = true
	            @roomId = cu.room_id
	          end
	        end
	      end

	      unless @isRoom
	        @room = Room.new
	        @entry = Entry.new
	      end
	    end
	end

	def edit
	end

	def update
		if @user.update(user_params)
	      redirect_to user_path(@user), notice: "You have updated user successfully."
	    else
	      render "edit"
	    end
	end

	def hide
	end

	def withdrawal
        @user.update(is_deleted: true)
        reset_session
        redirect_to root_path
	end


	private

    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :image, :area, :experience, :stance, :history, :introduction, :is_deleted)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Otoawase</title>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p&family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/5534b3fc8a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
    <header>
      <div class="top-icon"><%= link_to root_path do %>
        <%= image_tag asset_path('otoawase.png') %><% end %>
      </div>
      <nav class="nav">
        <div class="header-container clearfix">
          <ul class="nav-list">

            <!--ログイン時-->
            <% if user_signed_in? %>
              <li class="nav-list-item"　style="text-align: center;">
                <%= form_tag(search_path, :method => 'get') do %>
                  <%= text_field_tag 'search[content]' %>
                  <%= select_tag 'search[method]', options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
                  <%= submit_tag 'Search' %>
                <% end %>
              </li>
              <li class="nav-list-item"><%= link_to "マッチング一覧", user_relationships_index_path(current_user),class: "link" %></li>
              <li class="nav-list-item"><%= link_to "マイページ", user_path(current_user),class: "link" %></li>
              <li class="nav-list-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "link" %></li>
            <!-- ログイン外 -->
            <% else %>
              <li class="nav-list-item"　style="text-align: right;">
                <%= form_tag(search_path, :method => 'get') do %>
                  <%= text_field_tag 'search[content]' %>
                  <%= select_tag 'search[method]', options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
                  <%= submit_tag 'Search' %>
                <% end %>
              </li>
              <li class="nav-list-item"><%= link_to "About", users_about_path,class: "link" %></li>
              <li class="nav-list-item"><%= link_to "ログイン", new_user_session_path,class: "link" %></li>
              <li class="nav-list-item"><%= link_to "新規登録", new_user_registration_path,class: "link" %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <p id="notice"><%= notice %></p>
    <%= yield %>

    <footer>
      <div class="footer-container">
        <p class="copy">Copyright © yuichiro_saito All Rights Reserved.</p>
        <li class="footer-item"><%= mail_to 'kh.seasaltice.3745@gmail.com', "お問い合わせ",class: "link" %>
      </div>
    </footer>

  </body>
</html>